### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by ricoapon** [GreenT13/TaalmaatjesWebsite#14]
I should rewatch the tutorial about form validation and implement this into the screens with forms (at this moment add-volunteer + detail-volunteer/edit/...

**Comment by GreenT13** [comment]
Fixed in (part of) 8fd5beee292e17cd97b468cf909a6e0200badc87 and in a78bb0877acd6967dc13886f5d3daddf10f8b48e.

I now have a seperate component in which I can customize what to show in the tables. All works in the same way.

**Comment by ricoapon** [comment]
Form validation is easily done, but inputs should sit inside a form to make the form not-submittable.

This has as problem that everything must be inside a \<form\> tag, with a submit button. Not sure how this works with multiple components that are included inside a view (so \<form\> \<component with inputs\> \</form\>).

**Comment by ricoapon** [comment]
Fixed this in several commits.
